'''
base_exception.py의 500번 예외코드를 정의
'''
STATUS_RSP_INTERNAL_ERROR = {
    "status": 500,
    "message": "unknown error occurred."
}
